name: Pull Request Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Fetch oldversion.json from main
      run: |
        git fetch origin main:main
        git show main:tokenlist.json > oldversion.json

    - name: Run Tests
      run: npm test

    - name: Check Linting
      run: npm run lint

    - name: Check Formatting
      run: npm run format
